# Generated by Django 5.2.5 on 2025-09-08 05:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('atencion', models.CharField(blank=True, max_length=200, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='JOSE E. ALVARADO N.', max_length=200)),
                ('descripcion', models.TextField(default='SERVISIOS ELECTROMECANICOS\nINSTALACIÓN, MANTENCIÓN Y REPARACIÓN DE BOMBAS DE AGUA.\nSUPERFICIE Y SUMERGIBLES')),
                ('direccion', models.CharField(default='PJE. SANTA ELISA 2437 OSORNO', max_length=200)),
                ('telefono', models.CharField(default='9-76193683', max_length=100)),
                ('email', models.EmailField(default='J_ALVARADO33@HOTMAIL.COM', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(default='UND', max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Selección'), ('boolean', 'Sí/No')], max_length=20)),
                ('requerido', models.BooleanField(default=True)),
                ('opciones', models.TextField(blank=True, help_text='Para tipo select: opcion1,opcion2,opcion3', null=True)),
                ('valor_por_defecto', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('referencia', models.TextField()),
                ('lugar', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gastos_traslado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.tipotrabajo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_mano_obra', to='cotizaciones.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.IntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_servicio', to='cotizaciones.cotizacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_material', to='cotizaciones.cotizacion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.material')),
            ],
            options={
                'ordering': ['material__categoria', 'material__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroItemServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('item_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='cotizaciones.itemservicio')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.parametroservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(default='UND', max_length=50)),
                ('es_parametrizable', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.categoriaservicio')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='parametroservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='cotizaciones.serviciobase'),
        ),
        migrations.AddField(
            model_name='itemservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.serviciobase'),
        ),
        migrations.CreateModel(
            name='ItemPlantillaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_default', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('orden', models.IntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='cotizaciones.plantillacotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.serviciobase')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='plantillacotizacion',
            name='tipo_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.tipotrabajo'),
        ),
    ]
